### ISSUE TITLE
Weird behaviour main navigation + console errors

### ISSUE THREAD

**Issue by EnnioWolsink** [biz-dev-ops/md-docs-cli#473]
When navigating to a page referenced in the main navigation that is on the first level in the hierarchy, the subpages become visible and the minus-sign doesn't seem to work as expected. It does refresh the page and scrolls the viewport  to the top. And these errors appear:

<img width="645" alt="image" src="https://github.com/biz-dev-ops/md-docs-cli/assets/2317709/2ab0268b-a0a4-4ed1-88f3-baf76ed24ae0">

**Comment by arjangeertsema** [comment]
I cannot help you with this issue because I cannot reproduce the error. The problem should be in the content, so my advice is to remove content from the MD file until the problem disappears for root cause analysis.
