### ISSUE TITLE
Regression: directory names with a dot are no longer properly parsed

### ISSUE THREAD

**Issue by enniowolsinkRGN** [biz-dev-ops/md-docs-cli#786]
Reproduce:

1. Create a directory under `/docs` with a dot in it, ex: `2.0 category X`
2. Render the docs using the command `md-docs`
3. Verify the menu item of the directory is named `2` and not `2.0 category X` as expected

Broken in version: >= 1.1.22
Working version: 1.0.121 (and possibly newer ones)

**Comment by arjangeertsema** [comment]
@enniowolsinkRGN pull request 788 should fix the problem. Can you confirm?

**Comment by enniowolsinkRGN** [comment]
@arjangeertsema Indeed it's fixed! Can you release this fix with the next version? Thanks!
