### ISSUE TITLE
Regression: view source file button in menu no longer leads to file in repository

### ISSUE THREAD

**Issue by enniowolsinkRGN** [biz-dev-ops/md-docs-cli#787]
Reproduce:

1. Render the documentation using `md-docs`
2. Find the button with the Git logo in the menu on any page with the alt text **View source file** (displayed when hovered) and click on it. 
3. The link leads to the repository's main page but not the deep linked file.

**Comment by arjangeertsema** [comment]
The file attribute was added to urlTemplate in options.yml to support more complex git url implementations. 

This change was not documented in tests. This commit adds the correct example to options.yml: https://github.com/biz-dev-ops/md-docs-cli/commit/15de62f3af1811a0baeaa35305eee630f86e47df
